version: '3'

services:
  springboot:
    image: immagixe/cloud-file-storage
    restart: always
    depends_on:
      - mysql
      - minio
      - redis
    ports:
      - '8080:8080'
    environment:
      MINIO_URL: http://minio:9000
      ACCESS_KEY: "minioadmin"
      SECRET_KEY: "minioadmin"
      BUCKET_NAME: "user-files"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_user
      MYSQL_DATABASE: cloudfilestorage_db
    volumes:
      - mysql_data:/var/lib/mysql
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY_FILE: access_key
      MINIO_SECRET_KEY_FILE: secret_key
    volumes:
      - minio_storage:/data
  redis:
    image: redis
    volumes:
      - redis_storage:/data

volumes:
  mysql_data:
  minio_storage:
  redis_storage: