spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudFileStorage
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: user-files

url:
  schema: http
  host: localhost
  port: 8080